version: "3"

services:

  runtime-setup:
    image: swift-nio:default
    build:
      context: .
      dockerfile: Dockerfile

  common: &common
    image: swift-nio:default
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh
      - ..:/code
    working_dir: /code

  unit-tests:
    <<: *common
    command: /bin/bash -cl "swift test"

  rest:
    <<: *common
    tty: true
    ports:
      - "8010:8010"
    command: /bin/bash -cl "swift run SeagullRestDemo 0.0.0.0 8010"

  perf:
    <<: *common
    tty: true
    command: /bin/bash -cl "swift run SeagullPerfTest"
