version: "3"

services:

  runtime-setup:
    image: swift-nio:16.04-4.1
    build:
      args:
        ubuntu_version : "16.04"
        swift_version : "4.1"

  unit-tests:
    image: swift-nio:16.04-4.1

  rest:
    image: swift-nio:16.04-4.1

  simple:
    image: swift-nio:16.04-4.1
