version: "3"

services:

  runtime-setup:
    image: swift-nio:16.04-4.0.3
    build:
      args:
        ubuntu_version : "16.04"
        swift_version : "4.0.3"

  unit-tests:
    image: swift-nio:16.04-4.0.3

  base-srv:
    image: swift-nio:16.04-4.0.3

  simple-srv:
    image: swift-nio:16.04-4.0.3
